GRIP_F: 40
GRIP_VEL: 20
L_VEL: 20
J_VEL: 20
TCP_GP: [20, 0, 95,  0,  0,  0]
TCP_SK: [0, 0, 0, 0, 0, 0]
TCP_CA: [0, 0, 0, 0, 0, 0]
HOME_GP_J: [-45, 0, 0, 0, 45, 0]
HOME_SK_J: [0, 0, 0, 0, 0, 0]
HOME_CA_J: [0, 0, 0, 0, 0, 0]