TipCase:
  bottom_right:
    cartesian: [71.736, 331.11, -71.51, 100.47]
    joints: []
  bottom_left:
    cartesian: [71.736, 266.95, -71.51, 100.47]
    joints: []
  top_left:
    cartesian: [-26.75, 268.15, -71.51, 100.47]
    joints: []
  top_right:
    cartesian: [-26.75, 331.52, -71.51, 100.47]
    joints: []
Home: 
  cartesian: [0, 300, 112, 90]
  joints: [90, 0, 0, 0]