GRIP_F: 10
GRIP_VEL: 20
L_VEL: 10
J_VEL: 10
TCP_GP: [49.5, 0, 13.95, 45, 0, 0]
TCP_SK: [0, 0, 0, 0, 0, 0]
TCP_CA: [0, 0, 0, 0, 0, 0]
HOME_GP_J: [0, 0, 0, 0, 0, 0]
HOME_SK_J: [0, 0, 0, 0, 0, 0]
HOME_CA_J: [0, 0, 0, 0, 0, 0]
HOME_POST_J: [0, 0, 0, 0, 0, 0]
SNAP_SHOT_GRAB_PO: [0, 0, 0, 0, 0, 0]